apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8081
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8082
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8083
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8084
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 8080
        hostPort: 8085
        protocol: TCP

