apiVersion: v1
kind: Service
metadata:
  name: paxis
  labels:
    app: paxis
spec:
  selector:
    app: paxis
  clusterIP: None
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paxis
spec:
  serviceName: "paxis"
  replicas: 5
  template:
    metadata:
      name: paxis
      labels:
        app: paxis
    spec:
      containers:
        - name: paxis
          image: paxis:v1
          ports:
            - containerPort: 8080
              hostPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: ${HOSTNAME}
            - name: PAXOS_CLUSTER-SIZE
              value: "5"
            - name: PAXOS_NODE-LIST
              value: paxis-0,paxis-1,paxis-2,paxis-3,paxis-4
  selector:
    matchLabels:
      app: paxis

