spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/h2/test;Mode=MYSQL
    username: sa
    password: 123456
  jpa:
    database: h2
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: always
  h2:
    console:
      enabled: true
  application:
    name: paxis-instance1

paxos:
  cluster-size: 5
  idx: 0
  node-list: paxis-instance1,paxis-instance2,paxis-instance3,paxis-instance4,paxis-instance5
